name: egorozh_cv
description: "My site-card"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  slang: ^4.4.1
  slang_flutter: ^4.4.0
  slang_gpt: ^0.11.0

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  intl: any
  flutter_svg: ^2.0.17
  go_router: ^14.6.3
  flutter_markdown: ^0.7.5
  #  dio: ^5.4.3+1
  url_launcher: ^6.3.1
  freezed_annotation: ^2.4.4
  flutter_bloc: ^9.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  flutter_native_splash: ^2.4.4
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  json_serializable:

  injectable_generator: ^2.6.2
  slang_build_runner: ^4.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/splash.png
    - assets/mock_data/

flutter_native_splash:
  color: "#250036" #backgound color
  image: assets/splash.png
  web: true
