name: egorozh_cv
description: "My site-card"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  slang: ^3.32.0
  slang_flutter: ^3.32.0
  slang_gpt: ^0.10.3

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  intl: any
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.3
  flutter_markdown: ^0.7.3+1
  #  dio: ^5.4.3+1
  url_launcher: ^6.3.0
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  injectable: ^2.4.4
  get_it: ^7.7.0
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.1.0
  firebase_analytics: ^11.0.1
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  slang_build_runner: ^3.32.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/splash.png
    - assets/mock_data/

flutter_native_splash:
  color: "#250036" #backgound color
  image: assets/splash.png
  web: true
